export const UPDATE_USERS_LIST = 'UPDATE_USERS_LIST';
export const SEARCH_USERS_START = 'SEARCH_USERS_START'
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS'
export const SEARCH_USERS_FAIL = 'FETCH_INGREDIENTS_FAIL'
export const SET_USER = 'SET_USER';

export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_START = 'FETCH_USER_START'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'

export const FETCH_REPOS = 'FETCH_REPOS'
export const FETCH_REPOS_START = 'FETCH_REPOS_START'
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS'
export const FETCH_REPOS_FAIL = 'FETCH_REPOS_FAIL'


